### PR TITLE
Add a button to configure proxy #4

### PR DESCRIPTION
**Pull request by Ashwin2105**

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Hi @Ashwin2105 
Kindly post a screenshot!

**Comment by Ashwin2105** [comment]
#4

**Comment by shreyasbapat** [comment]
So, everytime a user opens the app, he gets to see two boxes to put proxy in?

**Comment by Ashwin2105** [comment]
Yes first to set http and other to set https

**Comment by shreyasbapat** [comment]
Maybe what we can do is, open up a separate window when user asks to set proxy? As this is not very user friendly.

**Comment by Ashwin2105** [comment]
I to thought of that but as a starter did this since it is easier.
Now working on that different window one.
can this be done using tkinter frame.

**Pull request closed without merging**
