### PR TITLE
Add threading for the UI to not freeze during the download process

### PR DESCRIPTION
**Pull request by Ashwin2105**
#14 
Created a new thread for downloading videos to prevent UI from freezing during downloading.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Travis doesn't support Python 3.7 andBlack doesn't support Python 3.5. So those two failures are not your fault. Look for Python 3.6. It's yours.

**Comment by shreyasbapat** [comment]
@Ashwin2105 Do you use primarily github for making changes?

Have a look at this:
https://github.com/shreyasbapat/YouTube-Downloader/blob/master/CONTRIBUTING.rst

You should follow this for making changes. Do you make a branch for making changes?

**Comment by shreyasbapat** [comment]
Always give proper titles to PRs

**Comment by Ashwin2105** [comment]
@shreyasbapat  is there any way to know exactly which lines of the code need reformatting??

**Comment by shreyasbapat** [comment]
Just run `black *.py` in your console.

And this will need a rebase :)

**Comment by shreyasbapat** [comment]
screenshot from 2018-12-29 13-30-08

Let me know if you want any help in rebasing. :)

**Pull request closed without merging**
